local S=require('SaveData') local H=require('ui.HUD') local A=require('fx.GameAudio')
local W=require('meta.WeeklyChallenge') local D=require('meta.DailyChallenge')
local T=require('meta.TotemSystem') local R=require('meta.RuneSystem')
local B=require('battle.BattleScene') local P=require('battle.Player') local L=require('battle.Loot')
local I=require('utils.I18n') local C=require('Config') local Wave=require('battle.Wave')
local mem={}
File=function(n,m)return {IsOpen=function()return m==FILE_WRITE or mem[n]~=nil end,ReadString=function()return mem[n] or '' end,WriteString=function(_,v)mem[n]=v end,Close=function()end}end
fileSystem.FileExists=function(_,n)return mem[n]~=nil end
local results={}
local function test(name,fn)local ok,e=pcall(fn);results[#results+1]={name=name,pass=ok,error=not ok and tostring(e) or nil}end
S.UnlockAll();S.highestWave=140;S.nickname='Test';S.equippedTotems={};S.equippedRunes={};S.relicLevels={}
test('Volume and mute persist independently',function()
 A.SetVolume(.37);A.SetMuted(true);H.SaveSettings();A.SetVolume(.9);A.SetMuted(false);H.LoadSettings()
 assert(A.volume==.37 and A.muted); A.SetMuted(false);assert(A.volume==.37)
 A.SetVolume(-1);assert(A.volume==0);A.SetVolume(4);assert(A.volume==1)
end)
test('Slider drag, clamp, mute toggle and release save',function()
 H.paused=true;H.volumeSlider={x=180,y=520,w=240};H.muteBtn={x=440,y=500,w=100,h=40}
 assert(H.HandleAudioTouch(300,520));assert(A.volume==.5);H.MoveAudioSlider(900);assert(A.volume==1)
 H.EndAudioDrag();assert(not H.audioDragging);assert(H.HandleAudioTouch(470,520));assert(A.muted)
 A.SetVolume(.6);assert(A.muted);A.SetMuted(false);H.paused=false
end)
test('Weekly entry selects a hero, back returns to weekly page',function()
 gameState=12;local _,day=W.GetSeasonInfo();HandleScreenTouch(360,186+(day-1)*56+20)
 assert(gameState==3,'selection was skipped');HandleCharSelectTouch(40,42);assert(gameState==12)
end)
test('Weekly selected hero starts weekly rules only',function()
 gameState=12;local _,day=W.GetSeasonInfo();HandleScreenTouch(360,186+(day-1)*56+20)
 HandleCharSelectTouch(588,375);HandleCharSelectTouch(360,674)
 assert(gameState==1 and W.active and not D.active);assert(P.charId=='bean','selected '..tostring(P.charId))
end)
test('Normal character back returns to title',function()
 gameState=12;local _,day=W.GetSeasonInfo();HandleScreenTouch(360,186+(day-1)*56+20)
 HandleCharSelectTouch(40,42);gameState=3;HandleCharSelectTouch(40,42);assert(gameState==0)
end)
test('Gold Digger adds drop probability and grants no regeneration',function()
 S.equippedTotems={{typeId='hp_regen',rarity='normal'}};D.Reset();W.Reset();B.Init('leaf');Wave.waveNum=10
 local b=T.CalcEquippedBonuses(S.equippedTotems);assert(b.goldDropBonus==.1 and b.hpRegenBonus==0)
 assert(P.totemGoldDropBonus==.1 and P.totemHpRegenBonus==0)
 P.totemLootBonus=0;P.lootBonus=0;assert(math.abs(L.CalcCoinDropChance()-(.36+.1)*1.8)<1e-8)
 P.regenRate=0;P.hp=10;P.Update(1,0,0);assert(P.hp==10)
 assert(T.TYPE_CONFIG.hp_regen.name=='掘金' and T.TYPE_CONFIG.hp_regen.unit=='%')
end)
test('Totem rarity boundaries: 75%,20%,4.5%,0.5%',function()
 local rng=math.random;local counts={};for i=1,1000 do math.random=function()return i end;local r=T.RollRarity();counts[r]=(counts[r] or 0)+1 end;math.random=rng
 assert(counts.junk==750 and counts.normal==200 and counts.rare==45 and counts.legendary==5)
end)
test('All 14 bosses map to runes; 5% boundary and no duplicates',function()
 local rng=math.random;local ok,e=pcall(function()
  for _,boss in ipairs(C.BOSSES)do local def=R.GetRuneByBoss(boss.id);assert(def,boss.id)
   math.random=function()return .05 end;assert(R.RollRune(boss.id,{}).id==def.id)
   assert(R.RollRune(boss.id,{[def.id]=true})==nil)
   math.random=function()return .050001 end;assert(R.RollRune(boss.id,{})==nil)
  end
 end);math.random=rng;assert(ok,e)
end)
test('Inventory persists totems and runes',function()
 S.totems={};S.ownedRunes={};assert(S.AddTotem({typeId='hp_regen',rarity='normal'}));assert(S.AddRune(R.RUNES[1].id))
 S.totems={};S.ownedRunes={};S.LoadProfile();assert(#S.totems==1 and S.ownedRunes[R.RUNES[1].id])
end)
test('Direct rune damage on boss grants drops exactly once',function()
 local E=require('battle.Enemy');W.Reset();D.Reset();S.equippedRunes={};S.equippedTotems={};S.totems={};S.ownedRunes={}
 B.Init('cat');E.Reset();P.invTimer=999;local e=E.SpawnBoss(P.x+100,P.y,C.BOSSES[1],1)
 local rng=math.random;local ok,err=pcall(function()
  math.random=function(a,b)if a then return a end return .01 end
  assert(E.Damage(e,1e9));assert(not E.Damage(e,1e9));B.Update(.01,0,0,720,1280)
  assert(#S.totems==1,'boss totem missing');assert(S.ownedRunes[R.RUNES[1].id],'boss rune missing')
  assert(P.kills==1);B.Update(.01,0,0,720,1280);assert(#S.totems==1 and P.kills==1,'duplicate settlement')
 end);math.random=rng;assert(ok,err)
end)
test('Normal projectile kills and pending queue do not duplicate drops',function()
 local E=require('battle.Enemy');local Pr=require('battle.Projectile');B.Init('cat');E.Reset();P.invTimer=999;S.totems={}
 local e=E.SpawnBoss(P.x+100,P.y,C.BOSSES[2],1)
 Pr.Spawn(e.x,e.y,e.x+1,e.y,1e9,0,nil,0);B.Update(.001,0,0,720,1280)
 assert(#S.totems==1 and P.kills==1);B.Update(.001,0,0,720,1280);assert(#S.totems==1 and P.kills==1)
end)
test('Daily wave rewards accumulate at configured thresholds',function()
 assert(D.CalcWaveReward(2)==0);assert(D.CalcWaveReward(3)==20);assert(D.CalcWaveReward(5)==70)
 assert(D.CalcWaveReward(10)==190);assert(D.CalcWaveReward(15)==390);assert(D.CalcWaveReward(20)==740)
 assert(D.GetRankBonus(1).gold==200 and D.GetRankBonus(2).gold==100 and D.GetRankBonus(3).gold==50)
end)
test('Unclaimed weekly reward survives restart and is paid once',function()
 W.seasonId=W.GetSeasonInfo();W.lastSeasonReward={gold=150,claimed=false};W.Save();W.lastSeasonReward=nil;W.Load()
 assert(W.lastSeasonReward and W.lastSeasonReward.gold==150);local before=S.metaGold
 assert(W.ClaimLastSeasonReward()==150);assert(S.metaGold==before+150)
 W.lastSeasonReward=nil;W.Load();assert(W.ClaimLastSeasonReward()==0)
end)
test('Season rollover preserves old pending rewards and survives a second load',function()
 W.seasonId='1999W01';W.seasonPoints=25;W.lastSeasonReward={gold=30,claimed=false};W.Save();W.Load()
 assert(W.lastSeasonReward.gold==180 and W.seasonPoints==0);W.Load();assert(W.lastSeasonReward.gold==180)
end)
test('Daily best survives JSON string keys',function()
 W.seasonId=W.GetSeasonInfo();W.seasonPoints=0;W.dailyPlayed={};W.RecordResult(10);W.Save();W.dailyPlayed={};W.Load()
 local earned=W.RecordResult(10);assert(earned==10,'bonus repeated: '..earned)
 local _,day=W.GetSeasonInfo();assert(W.GetWeekPreview()[day].bestWave==10)
end)
test('English exact catalog and composed labels',function()
 I.lang='en';for source,target in pairs(require('utils.English'))do assert(I.Localize(source)==target,source)end
 assert(I.Localize('通关第20波解锁')=='Clear wave 20 to unlock')
 assert(I.Localize('赛季积分: 25')=='Season points: 25')
 I.lang='zh';assert(I.Localize('掘金')=='掘金')
end)
OPTIMIZATION_RESULTS=results
A.SetVolume(1);A.SetMuted(false);H.paused=false;gameState=0
